name: 'interview_project'
version: '1.0.0'
config-version: 2

profile: 'interview_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
target-path: "target"
clean-targets:
  - "target"
  - "logs"

models:
  interview_project:
    materialized: table
    persist_docs: # in addition to DBT metadata also save docs in Postgres
      relation: true          # table/view comment
      columns: true           # column comments

    # Apply to models in folders:
    # Use + before the key to avoid confusion between configs and folders. Example:
    #    staging:
    #      +schema: staging
    staging:
      schema: staging

    mart:
      schema: mart

    report:
      schema: report
